### ISSUE TITLE
Dataset coverage during training

### ISSUE THREAD

**Issue by Shubham0209** [ysymyth/ec-nl#1]
Hello @ysymyth ,
If I have understood correctly, during each epoch out of all the N (=total images in the train dataset) only a set of n (=batch size*number of distracting images) is used as listener images [here](https://github.com/ysymyth/ec-nl/blob/master/ec-game/dataloader.py#L39). And n' (=batch size) is used as speaker images [here](https://github.com/ysymyth/ec-nl/blob/master/ec-game/dataloader.py#L38).  Hence it is a possibility that some images might be used repetitively and some may even not be used. How can we make sure that each of the image in training data is used as a speaker image at least once?

**Comment by ysymyth** [comment]
Hi, that's easy to fix. You can do something like this:

```python
# define a shuffled list of all indices
random_imgs = list(range(len(images)))
random.shuffle(random_imgs)
# later just take from the list
img_indices = random_imgs[batch_idx * num_dist: (batch_idx+1) * num_dist]
```
