### ISSUE TITLE
Multi-GPU support

### ISSUE THREAD

**Issue by Shubham0209** [ysymyth/ec-nl#3]
How can I train the model (EC game - used for generating the emergent language) on the multiple GPUs?

What are the necessary changes that need to be made to the code?

I really appreciate any help you can provide.

**Comment by ysymyth** [comment]
Hi, you can take a look at https://github.com/ysymyth/ec-nl/blob/master/ec-game/models.py and make speaker and listener multi-GPU. However, the EC game part should be very fast to run (just very simple RNN models, and not trained super long) even with one GPU -- I remember my experiments just took one hour or something. Let me know if you need more help!
